[package]
name = "build-rs-libnix"
version = "0.1.10"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
colored = { workspace = true }
regex = { workspace = true }
anyhow = { workspace = true }
